sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm

before_install:
    - export TZ='Asia/Shanghai'

install:
  - npm install  #安装hexo及插件

branches:
  only:
    - master # build master branch only
script:
  - hexo clean
  - hexo generate # generate static files

after_script:
  - git clone https://${GH_REF} .deploy_git  # GH_REF是最下面配置的仓库地址
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/   # 这一步之前的操作是为了保留master分支的提交记录，不然每次git init的话只有1条commit
  - cd ./public
  - git config --global user.name "bjdzliu"  #修改name
  - git config --global user.email "dezhaoliu@gmail.com"  #修改email
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"  # 提交记录包含时间 跟上面更改时区配合
  - git push --force --quiet "https://${Travis_Token}@${GH_REF}" master:master  #Travis_Token是在Travis中配置环境变量的名称
env:
 global:
   - GH_REF: github.com/bjdzliu/bjdzliu.github.io.git

notifications:
  email:
    - ldz_cll@outlook.com
  on_success: change
  on_failure: always


#deploy:
#  provider: pages
#  skip-cleanup: true
#  github-token: $GH_TOKEN
#  keep-history: true
#  on:
#    branch: master
#  local-dir: public
